services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - ${TRAEFIK_PORT}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5
    restart: unless-stopped
    environment:
      TINYAUTH_APPURL: ${TINYAUTH_APP_URL}
      TINYAUTH_AUTH_USERS: ${TINYAUTH_USERS}
      TINYAUTH_AUTH_TRUSTEDPROXIES: 172.30.0.0/24
      TINYAUTH_DATABASE_DRIVER: memory
      TINYAUTH_LOG_LEVEL: error
      TINYAUTH_UI_TITLE: Tinyauth Demo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.rule: Host(`${TRAEFIK_TINYAUTH_DOMAIN}`)
      traefik.http.routers.tinyauth.entrypoints: web
      traefik.http.services.tinyauth.loadbalancer.server.port: 3000
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth:3000/api/auth/traefik
      traefik.http.middlewares.tinyauth.forwardauth.authResponseHeaders: Remote-User,Remote-Name,Remote-Email,Remote-Groups,Remote-Sub

  demo:
    image: ghcr.io/tinyauthapp/demo:v0
    restart: unless-stopped
    environment:
      TINYAUTH_URL: ${TINYAUTH_APP_URL}
      DEMO_URL: ${DEMO_URL}
    labels:
      traefik.enable: true
      traefik.http.routers.demo.rule: Host(`${TRAEFIK_DEMO_DOMAIN}`)
      traefik.http.routers.demo.entrypoints: web
      traefik.http.services.demo.loadbalancer.server.port: 3000
      traefik.http.routers.demo.middlewares: tinyauth
      tinyauth.apps.demo.path.allow: ^\/$
      tinyauth.apps.demo.config.domain: ${TRAEFIK_DEMO_DOMAIN}

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/24
